title: Keystone Integrated Systems
description: "A trusted product engineering services company specializing in embedded systems, IoT development, and system integration for global clients."
author: Keystone Systems
url: "https://keystone-systems.github.io" # Make sure this is your correct GitHub Pages URL

# Social Media Links (for the footer)
twitter_username: your_twitter_handle
linkedin_company: your_linkedin_company_name
github_username:  your_github_username

# Build settings
theme: null
plugins:
  - jekyll-seo-tag