# _config.yml
title: Keystone Integrated Systems
description: "The Foundation for Your Innovation. We engineer robust, end-to-end solutions, seamlessly fusing hardware and software."
author: Keystone Systems
url: "https://keystone-systems.github.io" # IMPORTANT: Make sure this is your correct GitHub Pages URL

# Build settings
theme: null
plugins:
  - jekyll-seo-tag
